### ISSUE TITLE
Missing nginx_ensite & adminer after a successful installation.

### ISSUE THREAD

**Issue by valentine94** [vladdancer/drusible#11]

**Comment by valentine94** [comment]
nginx_ensite seems fixed via https://github.com/vladdancer/drusible/pull/17

**Comment by valentine94** [comment]
Also I think that the Adminer doesn't works because it's just isn't be enabled - because nginx_ensite was missing before, now it should works as expected.

**Comment by vladdancer** [comment]
Merged. Thanks.
